name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza diariamente
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the Snake
        uses: Platane/snk@v3
        with:
          github_user_name: emanuella7
          outputs: dist/snake.svg
      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
